version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # for AMQP
      - "15672:15672" # for RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  queue_mgt:
    build:
      context: .
      dockerfile: queueManagement.Dockerfile
    container_name: queue_mgt
    command: python queueMgt.py
    ports:
      - "5000:5000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=/run/secrets/firebase_key
      - FIREBASE_PROJECT_ID=your-project-id
    secrets:
      - firebase_key
    depends_on:
      - rabbitmq
    networks:
      - backend

  notification:
    build:
      context: .
      dockerfile: notification.Dockerfile
    container_name: notification
    command: python notification.py
    ports:
      - "5001:5000"
    environment:
      - TWILIO_ACCOUNT_SID=your_sid
      - TWILIO_AUTH_TOKEN=your_token
      - TWILIO_PHONE_NUMBER=+65xxxxxxx
    depends_on:
      - rabbitmq
    networks:
      - backend

secrets:
  firebase_key:
    file: ./hawkerflow-key.json

networks:
  backend:
    driver: bridge
