services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: RabbitMQ.Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  queuemgt:
    build:
      context: ./queuemgt
      dockerfile: queuemanagement.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/secrets/firebase-service-account.json
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  menu:
    build:
      context: ./menu
      dockerfile: menu.Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/secrets/firebase-service-account.json

  payment:
    build:
      context: ./payment
      dockerfile: payment.Dockerfile
    ports:
      - "5002:5002"

  ordermgt:
    build:
      context: ./ordermgt
      dockerfile: ordermanagement.Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/secrets/firebase-service-account.json
    environment:
      - RABBITMQ_HOST=rabbitmq

  activity:
    build:
      context: ./activity
      dockerfile: activity.Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/secrets/firebase-service-account.json
    environment:
      - RABBITMQ_HOST=rabbitmq

networks:
  default:
    name: hawker-network