services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # RabbitMQ UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  setup_rabbitmq:
    build:
      context: ./rabbitmq_setup
      dockerfile: setup.Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: on-failure
  
  queuemgt:
    build:
      context: ./queuemgt
      dockerfile: queuemanagement.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/app/firebase-cred.json
    depends_on:
      - setup_rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  menu:
    build:
      context: ./menu
      dockerfile: menu.Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/app/firebase-cred.json

  payment:
    build:
      context: ./payment
      dockerfile: payment.Dockerfile
    ports:
      - "5002:5002"

  ordermgt:
    build:
      context: ./ordermgt
      dockerfile: ordermanagement.Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - setup_rabbitmq
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/app/firebase-cred.json
    environment:
      - RABBITMQ_HOST=rabbitmq

  activity:
    build:
      context: ./activity
      dockerfile: activity.Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - setup_rabbitmq
    env_file:
      - .env
    volumes:
      - ./hawkerflow-is213-firebase-adminsdk-fbsvc-5225881c2e.json:/app/firebase-cred.json
    environment:
      - RABBITMQ_HOST=rabbitmq

networks:
  default:
    name: hawker-network