version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-management:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      # These environment variables can be used in your code (e.g., to locate your Firebase key)
      FIREBASE_SERVICE_ACCOUNT_KEY_PATH: /app/serviceAccount.json
      FIREBASE_PROJECT_ID: your-project-id
    volumes:
      - .:/app
