version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-management:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      MENU_SERVICE_URL: "http://menu_service:5001"
      PAYMENT_SERVICE_URL: "http://payment_service:5002"
      QUEUE_SERVICE_URL: "http://queue_service:5003"
      NOTIF_SERVICE_URL: "http://notif_service:5004"
      # Optionally set other variables (if needed)
    volumes:
      - .:/app
