openapi: 3.0.0
info:
  title: Order Management Service API
  version: "1.0.0"
paths:
  /order:
    post:
      summary: Create a new order
      description: >
        Accepts an order from the Customer UI, stores it in Firebase with a "pending" status,
        invokes the Payment service, and returns the order ID and pending status.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatus'
        '400':
          description: Bad Request
  /order/status/{orderId}:
    get:
      summary: Get order status
      description: Retrieves the current status of an order.
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
          required: true
          description: The unique identifier of the order.
      responses:
        '200':
          description: Order status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatus'
        '404':
          description: Order not found
components:
  schemas:
    OrderRequest:
      type: object
      properties:
        userId:
          type: integer
        email:
          type: string
          format: email
        stalls:
          type: object
          additionalProperties:
            type: object
            properties:
              dishes:
                type: array
                items:
                  type: integer
      required:
        - userId
        - email
        - stalls
    OrderStatus:
      type: object
      properties:
        orderId:
          type: string
        status:
          type: string
